name: ci
on: [push, pull_request]

permissions:
    pages: write
    contents: write

jobs:
    test-report:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v6

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                go-version-file: 'go.mod'
            - run: go version

            - name: Run tests
              continue-on-error: true
              run: go test -json ./... > go-test.jsonl

            - name: List all packages
              run: go list ./... > packages.txt

            - name: Generate test report
              run: go run ./cmd/testreport -pkgs packages.txt -in go-test.jsonl -out package-results.json

            - name: Pretty print report
              run: |
                jq . package-results.json

            - name: Upload test report artifact
              if: always()
              uses: actions/upload-artifact@v6
              with:
                name: test-report
                path: package-results.json
                retention-days: 7

            - name: Generate badges
              if: always()
              run: |
                rm -rf badges/tasks
                mkdir -p badges/tasks
                go run ./cmd/generate_badges -in package-results.json -out public/badges/tasks
                ls -la badges/tasks

            - name: Upload badges artifact
              if: always()
              uses: actions/upload-artifact@v6
              with:
                name: badges
                path: public/badges
                retention-days: 7

            - name: Commit and push badges
              run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git add badges/tasks/*.svg
                git commit -m "Update task badges" || exit 0
                git push

