name: ci
on: [push, pull_request]

permissions:
    pages: write
    contents: write

jobs:
    test-report:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v6

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                go-version-file: 'go.mod'
            - run: go version

            - name: Read baseline from config.json
              id: config
              run: |
                set -euo pipefail
                baseline_repo="$(jq -r '.diff.original.repo' ./.etc/config.json)"
                baseline_ref="$(jq -r '.diff.original.ref' ./.etc/config.json)"
                echo "baseline_repo=$baseline_repo" >> "$GITHUB_OUTPUT"
                echo "baseline_ref=$baseline_ref" >> "$GITHUB_OUTPUT"

            - name: Checkout baseline
              uses: actions/checkout@v6
              with:
                repository: ${{ steps.config.outputs.baseline_repo }}
                ref: ${{ steps.config.outputs.baseline_ref }}
                path: baseline
                fetch-depth: 1


            - name: Checkout diff
              uses: actions/checkout@v6
              with:
                path: current
                fetch-depth: 1

            - name: Diff
              run: |
                set -euo pipefail
                # git diff --no-index сравнивает две папки (не требует общей истории)
                # Важно: он возвращает exit code 1 когда есть отличия, поэтому "|| true"
                git -C  current diff --no-index --name-status ../baseline . > changed_files.txt || true
                awk '{print $2}' changed_files.txt | sort -u > changed_files_only.txt || true

                {
                  echo "Baseline: ${{ steps.config.outputs.baseline_repo }} @ ${{ steps.config.outputs.baseline_ref }}"
                  echo ""
                  echo "Changed files:"
                  cat changed_files.txt
                } >> "$GITHUB_STEP_SUMMARY"

            - uses: actions/upload-artifact@v6
              with:
                name: diff
                path: |
                  changed_files_only.txt 
                  changed_files.txt
            
            - name: del dirs
              run: |
                rm -rf current
                rm -rf baseline

            - name: Run tests
              continue-on-error: true
              run: go test -json ./... > go-test.jsonl

            - name: List all packages
              run: go list ./... > packages.txt

            - name: Generate test report
              run: go run ./cmd/testreport -pkgs packages.txt -in go-test.jsonl -out package-results.json -config ./.etc/config.json

            - name: Pretty print report
              run: |
                jq . package-results.json

            - name: Upload test report artifact
              if: always()
              uses: actions/upload-artifact@v6
              with:
                name: test-report
                path: package-results.json
                retention-days: 7

            - name: Generate badges
              if: always()
              run: |
                rm -rf badges/tasks
                mkdir -p badges/tasks
                go run ./cmd/generate_badges -in package-results.json -out badges/tasks
                ls -la badges/tasks

            - name: Upload badges artifact
              if: always()
              uses: actions/upload-artifact@v6
              with:
                name: badges
                path: public/badges
                retention-days: 7

            - name: Commit and push badges
              run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git add badges/tasks/*.svg
                git commit -m "Update task badges" || exit 0
                git push

    prepare_matrix:
        needs: test-report
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.mk.outputs.matrix }}
        steps:
            - name: Download results artifact
              uses: actions/download-artifact@v6
              with:
                name: test-report
                path: .

            - id: mk
              name: Build matrix from package-results.json
              shell: bash
              run: |
                matrix="$(jq -c '{
                include: [
                to_entries[]
                | select(.key | test("task_[0-9]+$"))
                | {
                    id: (.key | capture("task_(?<id>[0-9]+)$").id),
                    status: (.value.status // "unknown")
                    }
                ]
                }' package-results.json)"

                echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
                echo "$matrix"

    task:
        needs: prepare_matrix
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix: ${{ fromJson(needs.prepare_matrix.outputs.matrix) }}
        name: task ${{ matrix.id }}
        steps:
            - name: Set job result based on status
              shell: bash
              run: |
                st="${{ matrix.status }}"

                if [[ "$st" == "pass" ]]; then
                echo "task ${{ matrix.id }}: ok"
                exit 0
                elif [[ "$st" == "fail" ]]; then
                echo "task ${{ matrix.id }}: fail"
                exit 1
                else
                echo "::warning title=task ${{ matrix.id }}::unknown status '$st'"
                # джоба будет зелёной, но с warning в логах
                exit 0
                fi
    