name: test

on:
    push:
        branches: ["**"]
    pull_request:

jobs:
    go-test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v6

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                go-version-file: 'go.mod'
            - run: go version

            - name: Run tests
              continue-on-error: true
              run: go test -json ./... > go-test.jsonl

            - name: List all packages
              run: go list ./... > packages.txt

            - name: Generate test report
              run: go run ./cmd/testreport -pkgs packages.txt -in go-test.jsonl -out package-results.json

            - name: Show report in logs
              run:  |
                echo "==== package-results.json ===="
                cat package-results.json

            - name: Pretty print report
              run: |
                jq . package-results.json

            - name: Upload test report artifact
              if: always()
              uses: actions/upload-artifact@v6
              with:
                name: test-report
                path: package-results.json
                retention-days: 7
